### ISSUE TITLE
Convergence issues?

### ISSUE THREAD

**Issue by cnk113** [stephenslab/fastTopics#20]
Hello,

I've been trying to fit the model on my dataset, but it seems 1000+ iterations I still can't get the likelihood to plateau? There are many plateaus in the fitting, is this normal?
![image](https://user-images.githubusercontent.com/21249710/130362512-31f420b2-fbe9-4712-9c3f-fb372aa2f252.png)

Best,
Chang

**Comment by pcarbo** [comment]
@cnk113 This is interesting. I suspect that there are some interesting complexities to your data set. Can you tell me a little more about your data set? Are you usiing `fit_topic_model` or `fit_poisson_nmf`? There is some info on optimization in the [advanced vignette on single-cell data](https://stephenslab.github.io/fastTopics/articles/single_cell_rnaseq_practical.html) that you may find useful.

**Comment by cnk113** [comment]
Yeah, I should've clarified this isn't a normal matrix. It's a count matrix of exon/introns x cells so it's a bit bigger (and sparser) than gene x cell matrix.
I'm using fit_topic_model: `fit <- fit_topic_model(t(counts),k = 30, numiter.main=1000, numiter.refine = 1000)`

**Comment by pcarbo** [comment]
@cnk113 Yeah, so the issue is that you are increasing the number of EM iterations, which isn't really going to help you here; we use EM to obtain a good initial fit, but in many cases it has trouble converging, so we use the SCD method to more quickly obtain a solution (which is the default for `method.refine`). (Your example also suggests we may want to adjust the `fit_topic_model` defaults, or better clarify these points in the documentation.) Instead I would do something like this:

```R
fit <- fit_topic_model(t(counts),k = 30,numiter.main = 100,numiter.refine = 500)
```

For finer control you can also consider using `fit_poisson_nmf` followed by `poisson2multinom`.

Let me know if this doesn't resolve the difficulties.

**Comment by cnk113** [comment]
With the parameters set at 100 EM and 500 SCD iterations.
![image](https://user-images.githubusercontent.com/21249710/130576098-f245ad78-5440-4cb3-a806-7f354d8f514c.png)
However just for fun I ran really long in the background with 5000 EM and 5000 SCD iterations.
![image](https://user-images.githubusercontent.com/21249710/130576178-df008050-84af-4def-9a01-0bca846d427f.png)

**Comment by pcarbo** [comment]
Those plots confirm my suspicion that the EM has convergence difficulties in your example.
